name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
      run: |
          if [ -d tests ]; then
            python -m coverage run -m unittest
            python -m coverage json -o ./coverage/coverage-temp.json
            wget -O json-convert.py https://raw.githubusercontent.com/Alex286756/testing/main/json-convert.py
            python json-convert.py
          fi
    - name: Update Coverage Badge
      if: ${{ hashFiles('test') != '' }}
      uses: we-cli/coverage-badge-action@main
